from __future__ import annotations

import argparse
import hashlib
import json
import re
import tomllib
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw


PRODUCT_NAME = "gpbiometricspy Studio"
IDENTITY_SCHEMA = "gpbiometricspy-studio-windows-identity"
IDENTITY_SCHEMA_VERSION = 1
ICON_SIZES = (16, 24, 32, 48, 64, 128, 256)
TARGETS = {
    "browser": {
        "internal_name": "gpbiometricspy-studio",
        "original_filename": "gpbiometricspy-studio.exe",
        "file_description": "gpbiometricspy Studio",
    },
    "onefile": {
        "internal_name": "gpbiometricspy-studio-onefile",
        "original_filename": "gpbiometricspy-studio-onefile.exe",
        "file_description": "gpbiometricspy Studio",
    },
    "native": {
        "internal_name": "gpbiometricspy-studio-native",
        "original_filename": "gpbiometricspy-studio-native.exe",
        "file_description": "gpbiometricspy Studio Desktop",
    },
}


def _project_version(repo_root: Path) -> str:
    with (repo_root / "pyproject.toml").open("rb") as handle:
        data = tomllib.load(handle)
    version = str(data["project"]["version"]).strip()
    if not version:
        raise ValueError("project.version is empty")
    return version


def _copyright(repo_root: Path) -> str:
    text = (repo_root / "LICENSE").read_text(encoding="utf-8")
    match = re.search(r"^Copyright \(c\) .+$", text, flags=re.MULTILINE)
    if not match:
        raise ValueError("LICENSE does not contain the expected copyright line")
    return match.group(0).strip()


def windows_fixed_version(version: str) -> tuple[int, int, int, int]:
    """Map the project PEP 440 version to the four-integer Windows version tuple."""
    match = re.match(r"^(\d+(?:\.\d+){0,3})(.*)$", version)
    if not match:
        raise ValueError(f"Cannot derive a Windows version from {version!r}")

    release = [int(part) for part in match.group(1).split(".")]
    suffix = match.group(2)
    if len(release) > 4:
        raise ValueError(f"Windows fixed versions support at most four release components: {version!r}")

    release.extend([0] * (4 - len(release)))
    dev = re.search(r"(?:^|\.)dev(\d+)", suffix)
    if dev and release[3] == 0:
        release[3] = int(dev.group(1))

    if any(part < 0 or part > 65535 for part in release):
        raise ValueError(f"Windows fixed-version components must fit in 16 bits: {version!r}")
    return tuple(release)  # type: ignore[return-value]


def _version_text(identity: dict[str, Any]) -> str:
    fixed = tuple(identity["fixed_file_version"])
    strings = [
        ("FileDescription", identity["file_description"]),
        ("FileVersion", identity["file_version"]),
        ("InternalName", identity["internal_name"]),
        ("LegalCopyright", identity["legal_copyright"]),
        ("OriginalFilename", identity["original_filename"]),
        ("ProductName", identity["product_name"]),
        ("ProductVersion", identity["product_version"]),
    ]
    string_structs = ",\n                ".join(
        f"StringStruct({key!r}, {value!r})" for key, value in strings
    )
    return f"""# Generated by tools/pyinstaller/generate_windows_identity.py. Do not hand-edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fixed!r},
    prodvers={fixed!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
                {string_structs}
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def _draw_icon(path: Path) -> None:
    """Create a deterministic, dependency-light evaluation icon for Studio."""
    size = 256
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    # Rounded application tile.
    draw.rounded_rectangle((8, 8, 248, 248), radius=52, fill=(24, 38, 58, 255))
    draw.rounded_rectangle((20, 20, 236, 236), radius=42, outline=(104, 216, 196, 255), width=7)

    # A compact gaze/biometric mark: eye ring plus a signal trace.
    draw.ellipse((67, 58, 189, 180), outline=(238, 244, 248, 255), width=14)
    draw.ellipse((112, 103, 144, 135), fill=(104, 216, 196, 255))
    points = [(47, 188), (83, 188), (101, 163), (121, 214), (143, 151), (161, 188), (209, 188)]
    draw.line(points, fill=(238, 244, 248, 255), width=11, joint="curve")

    image.save(path, format="ICO", sizes=[(n, n) for n in ICON_SIZES])


def generate_identity(repo_root: Path, output_dir: Path, target: str) -> dict[str, Any]:
    if target not in TARGETS:
        raise ValueError(f"Unknown target {target!r}; expected one of {sorted(TARGETS)}")

    repo_root = repo_root.resolve()
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    package_version = _project_version(repo_root)
    fixed = windows_fixed_version(package_version)
    target_fields = TARGETS[target]
    identity: dict[str, Any] = {
        "schema": IDENTITY_SCHEMA,
        "schema_version": IDENTITY_SCHEMA_VERSION,
        "target": target,
        "package_version": package_version,
        "fixed_file_version": list(fixed),
        "file_version": ".".join(str(part) for part in fixed),
        "product_version": package_version,
        "product_name": PRODUCT_NAME,
        "file_description": target_fields["file_description"],
        "internal_name": target_fields["internal_name"],
        "original_filename": target_fields["original_filename"],
        "legal_copyright": _copyright(repo_root),
    }

    version_path = output_dir / "version-info.txt"
    icon_path = output_dir / "gpbiometricspy-studio.ico"
    manifest_path = output_dir / "windows-identity.json"

    version_path.write_text(_version_text(identity), encoding="utf-8", newline="\n")
    _draw_icon(icon_path)
    identity["version_resource_sha256"] = hashlib.sha256(version_path.read_bytes()).hexdigest()
    identity["icon_sha256"] = hashlib.sha256(icon_path.read_bytes()).hexdigest()
    manifest_path.write_text(json.dumps(identity, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    return identity


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate deterministic Windows identity resources for Studio.")
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--target", choices=sorted(TARGETS), required=True)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    identity = generate_identity(args.repo_root, args.output_dir, args.target)
    print(json.dumps(identity, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
